// <auto-generated />
using System;

using Aleph1.Skeletons.WebAPI.DAL.Implementation;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aleph1.Skeletons.WebAPI.DAL.Implementation.Migrations
{
	[DbContext(typeof(GenericContext))]
	[Migration("20220116165205_Person")]
	partial class Person
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "3.1.21")
				.HasAnnotation("Relational:MaxIdentifierLength", 128)
				.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("Aleph1.Skeletons.WebAPI.Models.Entities.Person", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int")
						.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

					b.Property<DateTimeOffset>("BirthDate")
						.HasColumnType("datetimeoffset");

					b.Property<string>("FirstName")
						.HasColumnType("varchar(max)")
						.IsUnicode(false);

					b.Property<string>("LastName")
						.HasColumnType("varchar(max)")
						.IsUnicode(false);

					b.HasKey("Id");

					b.ToTable("Person");
				});
#pragma warning restore 612, 618
		}
	}
}
